{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2019-15043",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://community.grafana.com/t/grafana-5-4-5-and-6-3-4-security-update/20569",
          "name": "https://community.grafana.com/t/grafana-5-4-5-and-6-3-4-security-update/20569",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://community.grafana.com/t/release-notes-v6-3-x/19202",
          "name": "https://community.grafana.com/t/release-notes-v6-3-x/19202",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/grafana/grafana/releases",
          "name": "https://github.com/grafana/grafana/releases",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://grafana.com/blog/2019/08/29/grafana-5.4.5-and-6.3.4-released-with-important-security-fix/",
          "name": "https://grafana.com/blog/2019/08/29/grafana-5.4.5-and-6.3.4-released-with-important-security-fix/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "In Grafana 2.x through 6.x before 6.3.4, parts of the HTTP API allow unauthenticated use. This makes it possible to run a denial of service attack against the server running Grafana."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2019-09-03T12:15Z",
  "lastModifiedDate": "2019-09-03T12:46Z"
}