{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2014-7143",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://www.openwall.com/lists/oss-security/2014/09/22/2",
          "name": "http://www.openwall.com/lists/oss-security/2014/09/22/2",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-7143",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-7143",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/96135",
          "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/96135",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://security-tracker.debian.org/tracker/CVE-2014-7143",
          "name": "https://security-tracker.debian.org/tracker/CVE-2014-7143",
          "refsource": "MISC",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Python Twisted 14.0 trustRoot is not respected in HTTP client"
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2019-11-12T14:15Z",
  "lastModifiedDate": "2019-11-12T14:45Z"
}