{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-1652",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/144724",
          "name": "ibm-mq-cve20181652-dos(144724)",
          "refsource": "XF",
          "tags": [

          ]
        },
        {
          "url": "https://www.ibm.com/support/docview.wss?uid=ibm10717483",
          "name": "https://www.ibm.com/support/docview.wss?uid=ibm10717483",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://www.ibm.com/support/docview.wss?uid=ibm10744557",
          "name": "https://www.ibm.com/support/docview.wss?uid=ibm10744557",
          "refsource": "CONFIRM",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM DataPower Gateway 7.1.0.0 through 7.1.0.19, 7.2.0.0 through 7.2.0.16, 7.5.0.0 through 7.5.0.10, 7.5.1.0 through 7.5.1.9, 7.5.2.0 through 7.5.2.9, and 7.6.0.0 through 7.6.0.2 and IBM MQ Appliance 8.0.0.0 through 8.0.0.8 and 9.0.1 through 9.0.5 could allow a local user to cause a denial of service through unknown vectors. IBM X-Force ID: 144724."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-12-11T16:29Z",
  "lastModifiedDate": "2018-12-11T16:29Z"
}